### ISSUE TITLE
Error on registration

### ISSUE THREAD

**Issue by escuco** [SamR1/FitTrackee#187]
I'm trying to install FitTrackee on [Uberspace](https://uberspace.de/). After some tinkering I've got the web backend working.

When I'm going to register my first user, I got the error message "`Error. Please try again or contact the administrator.`"
![screenshot-register-web-ui](https://user-images.githubusercontent.com/1647405/173766750-5a4b91ab-8dd9-4f3c-beaf-a55be15a22f9.JPG)

fittrackee.log:
```
2022/06/15 09:10:48 - fittrackee - ERROR - Exception on /api/auth/register [POST]
Traceback (most recent call last):
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 609, in connect
    sock = self.retry.call_with_retry(
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 610, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 675, in _connect
    raise err
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 663, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/fittrackee/users/auth.py", line 171, in register_user
    send_account_confirmation_email(new_user)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/fittrackee/users/auth.py", line 63, in send_account_confirmation_email
    account_confirmation_email.send(user_data, email_data)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask_dramatiq.py", line 173, in send
    return self.actor.send(*a, **kw)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/actor.py", line 111, in send
    return self.send_with_options(args=args, kwargs=kwargs)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/actor.py", line 130, in send_with_options
    return self.broker.enqueue(message, delay=delay)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 186, in enqueue
    self.do_enqueue(queue_name, message.options["redis_message_id"], message.encode())
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 278, in do_dispatch
    self._max_unpack_size(),
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 255, in _max_unpack_size
    cls._max_unpack_size_val = DEFAULT_LUA_MAX_STACK or self.scripts["maxstack"]()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5704, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5089, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5073, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/client.py", line 1232, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

When I now try to register again I got the message "`Sorry, that username is already taken.`"
But I can't login with my credentials.

I don't receive any register mails. 
These are my mail settings from .env:
```
# Emails
export UI_URL=fittrack.uber.space
export EMAIL_URL=smtp://mymail@mydomain.de:mypassword@my_mailserver.de:587/?tls=True
export SENDER_EMAIL=mail@domain.de
```

My username for smtp is my mail adress (with @) and my password has also a @ in it. So there are three @s in the mail string. Could that cause the problem?

Do you have any hints for me?
Thank you!

**Comment by SamR1** [comment]
Hi!

It  looks like the error is related to **Redis**:

```shell
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 663, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused
```

Your account was created, but since **FitTrackee** can not connect to **Redis**, no email was sent for account activation by **dramatiq** workers.

Is **Redis** installed and its URL set in configuration?  
By default, FitTrackee tries to connect to the local **Redis** instance:  
```shell
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

The [account activation through email](https://samr1.github.io/FitTrackee/installation.html#emails) is not mandatory (especially if it's a single-user instance).  
You can activate your account with [FitTrackee CLI](https://samr1.github.io/FitTrackee/cli.html#ftcli-users-update) (and set admin rights in the same time).

After activating the virtualenv:
```shell
$ source .env
$ ftcli users update jaykay --set-admin true
```

**Comment by escuco** [comment]
Thanks very much for your answer!

I've now installed Redis and startet the daemon with this [Uberspace guide](https://lab.uberspace.de/guide_redis/). 

Then I've change the configuration in .env and restartet FitTrackee:
`export REDIS_URL=redis://` 

But without any success. Has the URL to be different?

The uberspace documentation says "`Use the Unix socket ~/.redis/sock to access redis with other applications.`". So I tried `export REDIS_URL=/home/myusername/.redis/sock` in .env, but that also didn't work.

Apart from that, I was able to activate the user with FitTrackee CLI and to login after that - which is really cool. 

I'm going to use FitTrackee only with 3 or 4 known users, that can be registered manually by me - but it would be nice to get Redis working so that I can write a FitTrackee Guide on [lab.uberspace.de](https://lab.uberspace.de/).

**Comment by SamR1** [comment]
Can you try with `redis:\\` scheme?
```
export REDIS_URL=redis:///home/myusername/.redis/sock
```

(_Note that for now **FitTrackee** works like a single-user application. Even if several users can register, a user can only view his own workouts. I'm currently working on adding social features._)

**Comment by escuco** [comment]
> Can you try with `redis:\\` scheme?
> ```
> export REDIS_URL=redis:///home/myusername/.redis/sock
> ```

Unfortunatley that didn't work either:
```
2022/06/15 13:50:45 - fittrackee - ERROR - Exception on /api/auth/register [POST]
Traceback (most recent call last):
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 609, in connect
    sock = self.retry.call_with_retry(
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 610, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 675, in _connect
    raise err
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 663, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/fittrackee/users/auth.py", line 171, in register_user
    send_account_confirmation_email(new_user)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/fittrackee/users/auth.py", line 63, in send_account_confirmation_email
    account_confirmation_email.send(user_data, email_data)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask_dramatiq.py", line 173, in send
    return self.actor.send(*a, **kw)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/actor.py", line 111, in send
    return self.send_with_options(args=args, kwargs=kwargs)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/actor.py", line 130, in send_with_options
    return self.broker.enqueue(message, delay=delay)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 186, in enqueue
    self.do_enqueue(queue_name, message.options["redis_message_id"], message.encode())
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 278, in do_dispatch
    self._max_unpack_size(),
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 255, in _max_unpack_size
    cls._max_unpack_size_val = DEFAULT_LUA_MAX_STACK or self.scripts["maxstack"]()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5704, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5089, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5073, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/client.py", line 1232, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
(fittrackee) [fittrack@libra fittrackee]$ clear
(fittrackee) [fittrack@libra fittrackee]$ cat fittrackee.log
2022/06/15 13:50:45 - fittrackee - ERROR - Exception on /api/auth/register [POST]
Traceback (most recent call last):
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 609, in connect
    sock = self.retry.call_with_retry(
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 610, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 675, in _connect
    raise err
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 663, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/fittrackee/users/auth.py", line 171, in register_user
    send_account_confirmation_email(new_user)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/fittrackee/users/auth.py", line 63, in send_account_confirmation_email
    account_confirmation_email.send(user_data, email_data)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/flask_dramatiq.py", line 173, in send
    return self.actor.send(*a, **kw)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/actor.py", line 111, in send
    return self.send_with_options(args=args, kwargs=kwargs)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/actor.py", line 130, in send_with_options
    return self.broker.enqueue(message, delay=delay)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 186, in enqueue
    self.do_enqueue(queue_name, message.options["redis_message_id"], message.encode())
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 278, in do_dispatch
    self._max_unpack_size(),
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/dramatiq/brokers/redis.py", line 255, in _max_unpack_size
    cls._max_unpack_size_val = DEFAULT_LUA_MAX_STACK or self.scripts["maxstack"]()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5704, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5089, in evalsha
    return self._evalsha("EVALSHA", sha, numkeys, *keys_and_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/commands/core.py", line 5073, in _evalsha
    return self.execute_command(command, sha, numkeys, *keys_and_args)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/client.py", line 1232, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/home/fittrack/fittrackee/lib64/python3.9/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

> (_Note that for now **FitTrackee** works like a single-user application. Even if several users can register, a user can only view his own workouts. I'm currently working on adding social features._)

Social features (especially federation with ActivityPub/Mastodon) would be nice, but storing and viewing my personal activities from my Open Tracks App in a web based application is great for the moment. And FitTrackee looks really nice.

**Comment by SamR1** [comment]
Can you check **Redis** is running by connecting with the `redis-cli` (as described in [Userspace guide](https://lab.uberspace.de/guide_redis/))?  
If working correctly, maybe the user running **FitTrackee** hasn't permission to connect to **Redis**.

I tried to use socket on my dev instance, it works with socket path (in my case `export REDIS_URL=redis:///var/run/redis/redis.sock`)

**Comment by escuco** [comment]
Yes, everything seems fine:

```
(fittrackee) [fittrack@libra fittrackee]$ supervisorctl status redis
redis                            RUNNING   pid 32094, uptime 3:39:18
```
and

```
(fittrackee) [fittrack@libra fittrackee]$ redis-cli -s ~/.redis/sock
redis /home/fittrack/.redis/sock>
```
Tested with the same user that runs FitTrackee.

Could it be related to the fact that FitTrackee runs in that virtual environment? I'm not really into that python/pip/venv stuff.

**Comment by escuco** [comment]
If you mean `source .env` - yes, I did that, but without success.
If I'll find the time, I'm going to contact the uberspace support - maybe they've some ideas, what's going wrong with Redis.

**Comment by escuco** [comment]
Hello @SamR1 ,

I've got feedback from the Uberspace support. Their hint was, that FitTrackee maybe doesn't listen to the redis socket, but only to the standard TCP-Port. In the FitTrackee error logs repeatly appears the port 6379.

So they gave me the hint, to change the Redis service to listen to port 6379 instead of the socket - and that does the trick! Mails are being send correctly now :)

Maybe this could be a topic for you to mention in your documentation.

So many thanks for your patience! I'm going on now, having some tests and install FitTrackee from scratch again, to document and write down a howto guide for the [Uberlab](https://lab.uberspace.de/).

Jan

**Comment by SamR1** [comment]
Hi!

Thanks for the feedback, glad it's working :)

About Redis, it worked with socket when I tried. Maybe something is missing in Redis configuration?
