### ISSUE TITLE
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set (.env is correct and sourced)

### ISSUE THREAD

**Issue by gardiol** [SamR1/FitTrackee#574]
Hi!
fresh fittrackee PIP installation. I have created the postgres user and schema, and i am trying to run:
```
ftcli db upgrade
2024/06/19 15:20:26 - fittrackee - WARNING - Redis not available, API rate limits are disabled.
Traceback (most recent call last):
  File "/deposito/daemons/fittrackee/.local/bin/ftcli", line 5, in <module>
    from fittrackee.cli import cli
  File "/deposito/daemons/fittrackee/.local/lib/python3.11/site-packages/fittrackee/cli/__init__.py", line 3, in <module>
    from fittrackee.migrations.commands import db_cli
  File "/deposito/daemons/fittrackee/.local/lib/python3.11/site-packages/fittrackee/migrations/commands.py", line 9, in <module>
    from fittrackee.cli.app import app
  File "/deposito/daemons/fittrackee/.local/lib/python3.11/site-packages/fittrackee/cli/app.py", line 3, in <module>
    app = create_app(init_email=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deposito/daemons/fittrackee/.local/lib/python3.11/site-packages/fittrackee/__init__.py", line 89, in create_app
    db.init_app(app)
  File "/deposito/daemons/fittrackee/.local/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 310, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.
```

But i have the required envs:
```
(venv_ft) fittrackee@server ~ $ echo $DATABASE_URL 
postgresql://fittrackee:fittrackee@127.0.0.1:5432/
(venv_ft) fittrackee@server ~ $ cat .env 
PORT=5123
APP_SECRET_KEY=zzz
DATABASE_URL=postgresql://fittrackee:fittrackee@127.0.0.1:5432/
UI_URL=https://train.gardiol.org
EMAIL_URL=smtp://:@smtp.xxx.org:587/?tls=True
SENDER_EMAIL=xxx@yyy.org
```
(strings edited for privacy)

What could this be?

**Comment by SamR1** [comment]
Hi,

Does adding `export`  (like in the [example](https://github.com/SamR1/FitTrackee/blob/master/.env.example)) fix the issue?

**Comment by gardiol** [comment]
Yes!
Because i am an idiot :)
Of course.

thank you
