### ISSUE TITLE
column app_config.stats_workouts_limit does not exist

### ISSUE THREAD

**Issue by slackline** [SamR1/FitTrackee#619]
I updated from  `0.8.4` to `0.8.7` (and subsequently `0.8.8`) and see the following error on starting `fittrackee` under both newer versions...

```bash
2024/09/05 21:33:16 - fittrackee - ERROR - Exception on /api/config [GET]
Traceback (most recent call last):
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column app_config.stats_workouts_limit does not exist
LINE 1: ...acy_policy, app_config.about AS app_config_about, app_config...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/fittrackee/application/app_config.py", line 67, in get_application_config
    config = AppConfig.query.one()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
           ^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/fittrackee/.virtualenvs/fittrackee/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column app_config.stats_workouts_limit does not exist
LINE 1: ...acy_policy, app_config.about AS app_config_about, app_config...
                                                             ^

[SQL: SELECT app_config.id AS app_config_id, app_config.max_users AS app_config_max_users, app_config.gpx_limit_import AS app_config_gpx_limit_import,
app_config.max_single_file_size AS app_config_max_single_file_size, app_config.max_zip_file_size AS app_config_max_zip_file_size, app_config.admin_cont
act AS app_config_admin_contact, app_config.privacy_policy_date AS app_config_privacy_policy_date, app_config.privacy_policy AS app_config_privacy_poli
cy, app_config.about AS app_config_about, app_config.stats_workouts_limit AS app_config_stats_workouts_limit
FROM app_config]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

If I downgrade to `0.8.4` then the following packages are also downgraded and `fittrackee` works ok...

```bash
Installing collected packages: sqlalchemy, gunicorn, authlib, fittrackee
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.53
    Uninstalling SQLAlchemy-1.4.53:
      Successfully uninstalled SQLAlchemy-1.4.53
  Attempting uninstall: gunicorn
    Found existing installation: gunicorn 23.0.0
    Uninstalling gunicorn-23.0.0:
      Successfully uninstalled gunicorn-23.0.0
  Attempting uninstall: authlib
    Found existing installation: Authlib 1.3.2
    Uninstalling Authlib-1.3.2:
      Successfully uninstalled Authlib-1.3.2
  Attempting uninstall: fittrackee
    Found existing installation: fittrackee 0.8.8
    Uninstalling fittrackee-0.8.8:
      Successfully uninstalled fittrackee-0.8.8
Successfully installed authlib-1.3.0 fittrackee-0.8.4 gunicorn-22.0.0 sqlalchemy-1.4.52
```

Let me know if any more information is required.

**Comment by SamR1** [comment]
Hi,

The versions [v0.8.5](https://github.com/SamR1/FitTrackee/releases/tag/v0.8.5) and [v0.8.7](https://github.com/SamR1/FitTrackee/releases/tag/v0.8.7) contain database updates.  
Have the migrations been applied? (they are not executed automatically on [upgrade](https://samr1.github.io/FitTrackee/en/installation.html#upgrade))

**Comment by slackline** [comment]
Ahha, my apologies I hadn't read the upgrade section of the documentation, actually following the well documented upgrade instructions works perfectly. I must remember to read docs and avoid wasting others time.

Thank you for your patience and on-going development efforts.

**Comment by SamR1** [comment]
no problem :), glad it works.
